spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.215.104:3306/web?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: 5438027

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true



mybatis:
  type-aliases-package:com.opot.count.entity


server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 1800
